#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

set -e

source ./config

echo "Building Docker image..."
docker build -t master_${CONTAINER_NAME} ${PROJECT_ROOT}

echo "Running catkin_make..."
${PROJECT_ROOT}/script/run sh -c 'cd /catkin_ws/ && catkin_make'
