#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

set -e

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

source ./config

docker run -it \
  --name ${CONTAINER_NAME} \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --rm \
  --runtime=nvidia \
  --volume=$XSOCK:$XSOCK:rw \
  --volume=$XAUTH:$XAUTH:rw \
  --volume=$HOME:$HOME \
  --env="XAUTHORITY=${XAUTH}" \
  --env="DISPLAY=${DISPLAY}" \
  --env=TERM=xterm-256color \
  --env=QT_X11_NO_MITSHM=1 \
  --net=host \
  ${CONTAINER_NAME} "$@"

# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
