#!/bin/bash

# This is for non-device testing. Each user can run once such instance.

cd "$(dirname "${BASH_SOURCE[0]}")"

set -e

source ./config

CONTAINER_NAME=$(whoami)_$CONTAINER_NAME

if docker container inspect $CONTAINER_NAME >/dev/null 2>&1; then
	docker exec -it $CONTAINER_NAME /bin/bash	
else
	docker run -it \
	   --net=host \
	   --publish 11311:11311 \
	   --gpus all \
	   --name "$CONTAINER_NAME" \
	   --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
	   --rm \
	   --runtime=nvidia \
	   --env=DISPLAY \
	   -v /tmp/.X11-unix:/tmp/.X11-unix \
	   --security-opt seccomp=unconfined \
	   ${CONTAINER_NAME} "$@"
fi
