#!/bin/bash

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"
CONTAINER_NAME=ros-container

docker run -it \
  --name ${CONTAINER_NAME} \
  --volume ${PROJECT_ROOT}/catkin_ws:/catkin_ws \
  --rm \
  ${CONTAINER_NAME} "$@"

# Share a device with the Docker container by adding:
#   --device=/dev/ttyUSB0 \
# below the line containing "--name"
